version: '2'
services:
  database:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: easy-notes
    ports:
      - "27017:27017"
  application:
    build: ./
    depends_on: [database]
    links:
      - database
    ports:
      - "8080:8080"
