---
swagger: "2.0"
info:
  description: "TCO2018 Hello World"
  version: "1.0.0"
  title: "TCO2018 Hello World"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "hellowWorld.swagger.io"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /hello:
    get:
      summary: "Say Hello"
      description: ""
      operationId: "getGreeting"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Success"
      x-swagger-router-controller: "Default"
    post:
      summary: "Say Hello"
      description: ""
      operationId: "sendGreeting"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Send a greeting"
        required: true
        schema:
          $ref: "#/definitions/body"
      responses:
        200:
          description: "Greeted"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Default"
definitions:
  body:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
